name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start with PM2
        run: pm2 start src/index.js --name code-judge-api

      - name: Save PM2 process list
        run: pm2 save

      - name: Show running processes
        run: pm2 list